version: 2
jobs:
  build:
    working_directory: ~/ngcordova
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: ngcordova-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          key: ngcordova-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm test
