# version: 2
# jobs:
#   build:
#     working_directory:
#     docker:
#       - circleci/node:10-browsers
#     steps:
#       - checkout
#       - restore_cache:
#         key:
#       - run: npm i
#       - save_cache:
#         key:
#         paths:
#           - 'node_modules'
#       - run: npm test
